spring:
  datasource:
    url: jdbc:mysql://192.168.96.4:3306/ruoyi_james?serverTimezone=GMT%2B8
    username: root
    password: MyNewPass4!
  redis:
    host: 192.168.96.4
    database: 1
  jackson:
    default-property-inclusion: non_null
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
    serialization:
      indent_output: true
mybatis-plus:
  type-enums-package: com.cbest.ruoyijames.system.entity,com.cbest.ruoyijames.common.constant

logging:
  level:
    com.cbest.ruoyijames.system.mapper: debug
